stages:
- build
- test
- image

image: docker:19-git

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - docker
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
      --build-arg VCS_REF="$CI_COMMIT_SHA" --build-arg BUILD_DATE="$CI_JOB_STARTED_AT"
      --cache --cache-dir=/cache --cache-repo=${CI_REGISTRY_IMAGE}/testing
  after_script:
    - rm -f /kaniko/.docker/config.json

release:
  stage: image
  environment: release
  tags:
    - docker
  services:
    - docker:19-dind
  before_script:
    - mkdir -p /root/.docker
    - DH_AUTH=$(echo -n "${DH_USERNAME}:${DH_PASSWORD}" | base64)
    - >
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"},
      \"https://index.docker.io/v1/\":{\"auth\":\"$DH_AUTH\"}}}" > /root/.docker/config.json
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $DH_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $DH_REGISTRY_IMAGE:latest
    - docker push $DH_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $DH_REGISTRY_IMAGE:latest
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker rmi $DH_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker rmi $CI_REGISTRY_IMAGE:latest
    - docker rmi $DH_REGISTRY_IMAGE:latest
  after_script:
    - rm -f /root/.docker/config.json
  only:
    - tags
